<div class="jumbotron">
    <h1>Welcome to <span class="zf-green">Linux Web App</span></h1>

    <p>
        Congratulations! You have successfully installed PHP application on Linux Web App
        <a href="https://github.com/zendframework/ZendSkeletonApplication" target="_blank">PHP application using Zend Framework</a>.
        <!--  You are currently running Zend Framework version <?= \Application\Module::VERSION ?>. -->
        Azure Web App on Linux is currently in public preview and supports running web apps natively on Linux. This skeleton can serve as a simple starting point for you to begin
        building your application on ZF on Linux Web App. 
    </p>

    <p><a class="btn btn-success btn-lg" href="https://github.com/SunBuild/zend-demo-app" target="_blank">Fork this application from Github</a></p>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Get Started</h3>
            </div>
            <div class="panel-body">
            <ul>
            <li><a href="https://docs.microsoft.com/en-us/azure/app-service-web/app-service-linux-intro" > What is Web App on Linux </a> </li>
            <li><a href="https://azure.microsoft.com/en-us/pricing/details/app-service/">Microsoft Azure App Service pricing </a></li>
            <li><a href="https://docs.microsoft.com/en-us/azure/app-service-web/app-service-linux-how-to-create-web-app">Create Web app on Linux</a></li>
            
            </ul>               
                <p><a class="btn btn-success pull-right" href="https://docs.microsoft.com/en-us/azure/app-service/app-service-linux-readme" target="_blank">Documentation</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Bring your own Docker container</h3>
            </div>
            <div class="panel-body">
              <ul>                          
              <li> <a href="https://docs.microsoft.com/en-us/azure/app-service-web/app-service-linux-using-custom-docker-image">Using custom docker image with Linux on Web App</a></li>
              <li><a href="https://docs.microsoft.com/en-us/azure/app-service-web/app-service-linux-ci-cd"> Continuous Deployment with Docker Hub </a> </li>
              <li><a href="https://docs.microsoft.com/en-us/azure/app-service-web/app-service-linux-faq">Web App on Linux FAQ </a></li>
              </ul>

                <p><a class="btn btn-success pull-right" href="https://hub.docker.com/r/appsvc" target="_blank">Explore our docker images</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Samples and Support</h3>
            </div>
            <div class="panel-body">
                <ul>
                <li><a href="https://github.com/azure-samples">Samples</a></li>
                <li><a href="https://social.msdn.microsoft.com/forums/azure/en-us/home?forum=windowsazurewebsitespreview">Forums</a></li>
                <li><a href="https://stackoverflow.com/questions/tagged/azure-web-app-service"> StackOverflow</a> </li>
                </ul>

                <p><a class="btn btn-success pull-right" href="https://azure.microsoft.com/en-us/support/options/" target="_blank">Azure Support</a></p>
            </div>
        </div>
    </div>
</div>
